services:
  mongodb:
    image: mongo:8
    container_name: ai-dubbing-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db


  redis:
    image: redis:7-alpine
    container_name: ai-dubbing-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: ai-dubbing-backend
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

    depends_on:
      - mongodb
      - redis
      - stt
      - translation
      - tts


  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: ai-dubbing-worker
    restart: unless-stopped

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

    depends_on:
      - mongodb
      - redis
      - stt
      - translation
      - tts

    command: node workers/dubbing.worker.js


  stt:
    build:
      context: ./stt
      dockerfile: Dockerfile

    container_name: ai-dubbing-stt
    restart: unless-stopped

    ports:
      - "8000:8000"


  translation:
    build:
      context: ./translation
      dockerfile: Dockerfile

    container_name: ai-dubbing-translation
    restart: unless-stopped

    ports:
      - "8001:8001"


  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile

    container_name: ai-dubbing-tts
    restart: unless-stopped

    ports:
      - "8002:8002"

    volumes:
      - ./backend/temp:/shared
      - ./tts/models:/models:ro


volumes:
  mongodb_data:
  redis_data:
  backend_node_modules: