services:
  mongodb:
    image: mongo:8
    container_name: ai-dubbing-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: ai-dubbing-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: ai-dubbing-backend
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      - mongodb
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: ai-dubbing-worker
    restart: unless-stopped

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      - mongodb
      - redis

    command: node workers/dubbing.worker.js

volumes:
  mongodb_data:
  redis_data:
